# Generated by Django 4.1.4 on 2022-12-13 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commntPost',
            new_name='commentPost',
        ),
    ]
